blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/aygp-dr/isolated-pymcp/discussions
    about: Please ask general questions or start discussions here